export const CarBrand = {
  'ACURA': 'Acura',
  'ALFA_ROMEO': 'Alfa Romeo',
  'AUDI': 'Audi',
  'BAIC': 'BAIC',
  'BMW': 'BMW',
  'BRILLIANCE': 'Brilliance',
  'BUICK': 'Buick',
  'BYD': 'BYD',
  'CADILLAC': 'Cadillac',
  'CHANGAN': 'Changan',
  'CHERY': 'Chery',
  'CHEVROLET': 'Chevrolet',
  'CHRYSLER': 'Chrysler',
  'CITROEN': 'Citroen',
  'DACIA': 'Dacia',
  'DAEWOO': 'Daewoo',
  'DAIHATSU': 'Daihatsu',
  'DATSUN': 'Datsun',
  'DODGE': 'Dodge',
  'DONGFENG': 'DongFeng',
  'EVOLUTE': 'Evolute',
  'EXEED': 'Exeed',
  'FAW': 'FAW',
  'FIAT': 'Fiat',
  'FORD': 'Ford',
  'GAC': 'GAC',
  'GEELY': 'Geely',
  'GENESIS': 'Genesis',
  'GREAT_WALL': 'Great Wall',
  'HAIMA': 'Haima',
  'HAVAL': 'Haval',
  'HONDA': 'Honda',
  'HYUNDAI': 'Hyundai',
  'INFINITI': 'Infiniti',
  'IRAN_KHODRO': 'Iran Khodro',
  'JAC': 'JAC',
  'JAGUAR': 'Jaguar',
  'JEEP': 'Jeep',
  'JETTA': 'Jetta',
  'KAIYI': 'Kaiyi',
  'KIA': 'Kia',
  'LADA_(ВАЗ)': 'LADA (ВАЗ)',
  'LAND_ROVER': 'Land Rover',
  'LEXUS': 'Lexus',
  'LIFAN': 'Lifan',
  'MAZDA': 'Mazda',
  'MERCEDES_BENZ': 'Mercedes-Benz',
  'MG': 'MG',
  'MINI': 'MINI',
  'MITSUBISHI': 'Mitsubishi',
  'MOBILIZE': 'Mobilize',
  'NISSAN': 'Nissan',
  'OMODA': 'Omoda',
  'OPEL': 'Opel',
  'PEUGEOT': 'Peugeot',
  'PORSCHE': 'Porsche',
  'RAVON': 'Ravon',
  'RENAULT': 'Renault',
  'SAAB': 'Saab',
  'SCION': 'Scion',
  'SEAT': 'SEAT',
  'SKODA': 'Skoda',
  'SSANGYONG': 'SsangYong',
  'SUBARU': 'Subaru',
  'SUZUKI': 'Suzuki',
  'TESLA': 'Tesla',
  'TOYOTA': 'Toyota',
  'VOLKSWAGEN': 'Volkswagen',
  'VOLVO': 'Volvo',
  'VORTEX': 'Vortex',
  'XPENG': 'Xpeng',
  'ZOTYE': 'Zotye',
  'МОСКВИЧ': 'Москвич',
  'HONGQI': 'Hongqi',
  'MASERATI': 'Maserati',
  'VOYAH': 'Voyah',
  'ZEEKR': 'Zeekr',
}

