export const ORDER_SERVICE_TOKEN = Symbol('ORDER_SERVICE')
export const ORDER_SERVICE_BROKER_TOKEN = Symbol('ORDER_SERVICE_BROKER')
export const ORDER_SERVICE_ASYNC_TOKEN = Symbol('ORDER_SERVICE_ASYNC')
export const AUTH_SERVICE_TOKEN = Symbol('AUTH_SERVICE')
