export { SavedAddressRelations } from '@infrastructure/persistent/pg/migrations/table-relations/1700007923-saved-address-relations'
export { PassengerRelations } from '@infrastructure/persistent/pg/migrations/table-relations/1700008390-passenger-relations'
export { DriverRelations } from '@infrastructure/persistent/pg/migrations/table-relations/1700008494-driver-relations'
export { CarRelations } from '@infrastructure/persistent/pg/migrations/table-relations/1700008606-car-relations'
export { PriceSegmentRequirementRelations } from '@infrastructure/persistent/pg/migrations/table-relations/1700008825-price-segment-requirement-relations'
export { ShiftRelations } from '@infrastructure/persistent/pg/migrations/table-relations/1700008834-shift-relations'
export { OrderRelations } from '@infrastructure/persistent/pg/migrations/table-relations/1700009049-order-relations'
export { PriceProposeRelations } from '@infrastructure/persistent/pg/migrations/table-relations/1700009151-price-propose-relations'
