version: "3.9"

services:
  rabbitmq-test:
    container_name: ${PROJECT_NAME}-rabbit-test
    build: ./images/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - ${RABBITMQ_GUI_PORT}:15672
      - ${RABBITMQ_AMQP_PORT}:5672

  postgres-test:
    container_name: ${PROJECT_NAME}-postgres-test
    build: ./images/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    volumes:
      - pgdata:${PGDATA}
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  pgdata:
